export const bankLogos = {
  "Access Bank": "https://example.com/logos/access-bank.png",
  "Access Diamond": "https://example.com/logos/access-diamond.png",
  GTB: "https://example.com/logos/gtb.png",
  "First Bank": "https://example.com/logos/first-bank.png",
  "Zenith Bank": "https://example.com/logos/zenith.png",
  UBA: "https://example.com/logos/uba.png",
  "Stanbic Bank": "https://example.com/logos/stanbic.png",
  "Sterling Bank": "https://example.com/logos/sterling.png",
  "Unity Bank": "https://example.com/logos/unity.png",
  "Keystone Bank": "https://example.com/logos/keystone.png",
  "Fidelity Bank": "https://example.com/logos/fidelity.png",
  Ecobank: "https://example.com/logos/ecobank.png",
  "Wema Bank": "https://example.com/logos/wema.png",
  FCMB: "https://example.com/logos/fcmb.png",
  "Rubies Highstreet MFB": "https://example.com/logos/rubies.png",
  "VFD MFB": "https://example.com/logos/vfd.png",
  "Union Bank": "https://example.com/logos/union.png",
  "Kuda Bank": "https://example.com/logos/kuda.png",
  "Premium Trust Bank": "https://example.com/logos/premium-trust.png",
  "Lotus bank": "https://example.com/logos/lotus.png",
  "Optimus bank": "https://example.com/logos/optimus.png",
  "Carbon MFB": "https://example.com/logos/carbon.png",
  "Parallex bank": "https://example.com/logos/parallex.png",
  "Heritage Bank": "https://example.com/logos/heritage.png",
  "Globus bank": "https://example.com/logos/globus.png",
};
